
* galaxian.inc

***    
*** BUILD OPTIONS
***

    * hardware options
    OPT_DISABLE_BG_LAYER=0
    OPT_DISABLE_SPRITES=0
    OPT_DISABLE_DISPLAY_MASKS=0
   
    * score is BCD format
    OPT_START_SCORE=0x0000000
	
***
*** end of BUILD OPTIONS
***




* sound ordinals

    .equ  CREDIT_SND,         0x00
    .equ  SHOOT_SND,         0x01
    .equ  INTRO_SND,      0x02
    .equ  ALIEN_SHOT_SND,      0x03
    .equ  FLAGSHIP_SHOT_SND,      0x04
    .equ  PLAYER_SHOT_SND,      0x05


    
